name: Deploy React in Firebase

on:
    push:
        branches: 
          - main
          - 'release/**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Set Environment Variable
              run: |
                if [[ "${GITHUB_REF#refs/heads/}" =~ ^release.* ]]; then
                    echo "TARGET=prod-game-of-life" >> $GITHUB_ENV
                else
                    echo "TARGET=dev-game-of-life" >> $GITHUB_ENV
                fi

            - name: Install dependencies
              run: npm install

            - name: Run lint, test and build
              run: |
                npm run lint
                npm run test
                npm run build

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                args: deploy --only hosting:$TARGET
              env:
                GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

